### ISSUE TITLE
No longer retrieving data

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/campbelltown#3]
http://www.planningalerts.org.au/authorities/campbelltown suggests this is no longer working.

Manually going through the process, you need to hit

http://www.campbelltown.nsw.gov.au/DevelopmentOnlineservices
then
https://ebiz.campbelltown.nsw.gov.au/ePathway/Production/Web/GeneralEnquiry/EnquirySummaryView.aspx

otherwise you get authentication errors.

**Comment by henare** [comment]
I think this was fixed in #4.
